version: "3"
services:
  mapiacompany_db:
    image: neo4j:4.3
    container_name: mapiacompany_db
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - ./database:/data
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    platform: linux/x86_64
  mapiacompany_backend:
    build:
      context: .
      dockerfile: ./Dockerfile-dev-local
    container_name: mapiacompany_backend
    ports:
      - 8000:8000
    depends_on:
      - mapiacompany_db
    restart: always
    environment:
      - NEOMODEL_NEO4J_BOLT_URL=bolt://neo4j:test@mapiacompany_db:7687
      - DJANGO_SETTINGS_MODULE=mapiacompany.settings.dev_local
    env_file:
      - .dockerenv.dev_local
    platform: linux/x86_64
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
