from .base   import *

ALLOWED_HOSTS = ['*']

SECRET_KEY = get_env_variable('DJANGO_SECRET_KEY')
DEBUG      = False

NEOMODEL_NEO4J_BOLT_URL = get_env_variable('NEOMODEL_NEO4J_BOLT_URL')
NEOMODEL_SIGNALS = True
NEOMODEL_FORCE_TIMEZONE = False
NEOMODEL_MAX_CONNECTION_POOL_SIZE = 50